Friends/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get 'hom/ind'
  #get 'home/index'
  get 'home/about'
 #root 'home#index'
 root 'friends#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Friends/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Friends/app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

Friends/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends
end

Friends/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Friends/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
   # @friend = Friend.new
   @friend= current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend= current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorised to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter,:user_id)
    end
end

Friends/app/controllers/hom_controller.rb
class HomController < ApplicationController
  def ind
  end
end

Friends/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me="My Name is Swetha"
  end
end

Friends/app/helpers/application_helper.rb
module ApplicationHelper
end

Friends/app/helpers/friends_helper.rb
module FriendsHelper
end

Friends/app/helpers/hom_helper.rb
module HomHelper
end

Friends/app/helpers/home_helper.rb
module HomeHelper
end

Friends/app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name ,class:'form-control',placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name ,class:'form-control',placeholder:"Last Name"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :email ,class:'form-control',placeholder:"Email"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone ,class:'form-control',placeholder:"Phone"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :twitter ,class:'form-control',placeholder:"Twitter"%>
  </div>
  <div class="field form-group">
    <%= form.number_field :user_id ,class:'form-control',id: :friend_user_id,value:current_user.id,type: :hidden%>
  </div>
</br>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary'%>
  </div>
<% end %>

Friends/app/views/friends/edit.html.erb
<h1>Editing Friend</h1>
<br/>
<%= render 'form', friend: @friend %>
<br/>
<%= link_to 'Show', @friend ,class:"btn btn-secondary"%> 
<%= link_to 'Back', friends_path,class:"btn btn-secondary" %>
<%= link_to 'Delete', @friend, class:"btn btn-danger",method: :delete, data: { confirm: 'Are you sure?' } %>

Friends/app/views/friends/index.html.erb
<%if user_signed_in?%>
<h1>Friends</h1>
  <table class="table table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>

        <th> </th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <%if friend.user==current_user%>
          <tr>
            <td>
            <%= link_to friend.first_name + ' ' + friend.last_name, friend %>
            </td>
            <td><%= friend.email %></td>
            <td><%= friend.phone %></td>
            <td><%= friend.twitter %></td>
            <td><%= link_to 'Delete', friend, class:"btn btn-outline-danger btn-sm",method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <%end%>
      <% end %>
    </tbody>
  </table>
<br>

<%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary"%>
<%else%>
  <h1>Home index</h1>
  This is my first rails webpage

<%end%>

Friends/app/views/friends/new.html.erb
<h1>Add New Friend</h1>

<%= render 'form', friend: @friend %>
</br>
</br>
<%= link_to 'Back', friends_path,class:"btn btn-secondary"  %>

Friends/app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead">
  <%= @friend.email %>|
  <%= @friend.phone %>|
  <%= @friend.twitter %>
  </p>
  <%= link_to 'Edit', edit_friend_path(@friend),class:"btn btn-secondary" %> 
  <%= link_to 'Back', friends_path,class:"btn btn-secondary" %>
  <%= link_to 'Delete', @friend, class:"btn btn-danger",method: :delete, data: { confirm: 'Are you sure?' } %>


</div>

Friends/app/views/hom/ind.html.erb
<h1>Hom#ind</h1>
<p>Find me in app/views/hom/ind.html.erb</p>

Friends/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<%= link_to 'Friend App',root_path,class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'About us',home_about_path,class:"nav-link"%>
      </li>
      
      
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign Out',destroy_user_session_path,method: :delete,class:"nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to 'Edit Profile',edit_user_registration_path,class:"nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to 'Add New Friend',new_friend_path,class:"nav-link"%>
        </li>
        
      
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up',new_user_registration_path,class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In',new_user_session_path,class:"nav-link"%>
        </li>
      <% end %>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

Friends/app/views/home/about.html.erb
<h1>about us</h1>
<p><%= @about_me%>

Friends/app/views/home/index.html.erb
<h1>Home index</h1>
This is my first rails webpage

Friends/app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice%>
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	    <span aria-hidden="true">&times;</span>
	  </button>
  </div>
  

Friends/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    

  </head>

  <body>
    <%= render 'home/header'%>
    <div>
      <% if notice %>
        <%= render 'layouts/alerts'%>
      <% end%>
    </div>
  
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      $('.alert').alert()
   })
  </script>
  </br>
    <%= yield %>
  </body>
</html>